import { ApiProperty } from '@nestjs/swagger';

export class CreateDeviceDto {
  @ApiProperty({
    example: 'portatil-gabriel',
  })
  readonly id_estacion: string;

  @ApiProperty({ example: '10-10-2022-00:00:01' })
  timestamp: string;

  @ApiProperty({ example: 'Gabriel Morales' })
  readonly name: string;
  
  @ApiProperty({ example: 'reg/app' })
  readonly topic: string; 

  @ApiProperty({ example: 'This token will be autogenerated' })
  token: string; 

  @ApiProperty({ example: 'Name of the room' })
  room: string; 

  @ApiProperty({ example: 'Building where room is located' })
  building: string; 

  @ApiProperty({ example: 'Value of latitude' })
  latitude: string; 

  @ApiProperty({ example: 'Value of longitude' })
  longitude: string; 
}

